### ISSUE TITLE
Container with command is not launched with the arguments in the specified order (alphabettically sorted)

### ISSUE THREAD

**Issue by franckOL** [eclipse-iofog/Agent#367]
The Application template contains:
```yaml
          commands:
            - '/usr/bin/contextBroker'
            - '-fg'
            - '-multiservice'
            - '-ngsiv1Autocast'
            - '-dbhost'
            - 'localhost:2017'
            - '-corsOrigin'
            - '__ALL'
```

After instanciation and deployement 
```bash
 iofogctl describe microservice
```
shows:
```yaml
    commands:
    - /usr/bin/contextBroker
    - -fg
    - -multiservice
    - -ngsiv1Autocast
    - -dbhost
    - localhost:2017
    - -corsOrigin
    - __ALL
```

But running container get:
```bash
/usr/bin/contextBroker -fg -multiservice -ngsiv1Autocast -corsOrigin -dbhost -fg -mult
iservice -ngsiv1Autocast /usr/bin/contextBroker __ALL localhost:2017
```

**Comment by NehaNaithani** [comment]
Hi Frank, thanks for reporting the issue. Could you please share the yaml used so that we can recreate the issue and fix it for you asap.

**Comment by NehaNaithani** [comment]
Hi @franckOL,
I am using the below dev version `iofogctl` , `controller` and `agent` for testing
```
Agent: 2.0.0-dev
Controller: 2.1.0-dev-b11428
iofogctl: 2.0.3-dev
```
I tried to reproduce the issue with the below yaml
```
apiVersion: iofog.org/v2
kind: AgentConfig
metadata:
  name: neha-rpi # ioFog Agent name
spec:
  # All fields are optional - Only the specified fields will be updated
  bluetoothEnabled: true
  abstractedHardwareEnabled: false
---
kind: Application
apiVersion: iofog.org/v2
metadata:
  name: "healthcarewearableflow1"
spec:
  microservices:
    # Custom micro service that will connect to Scosche heart rate monitor via Bluetooth
    - name: heart-rate-monitor1
      agent:
        name: "neha-rpi"
        config:
          bluetoothEnabled: true # this will install the iofog/restblue microservice
          abstractedHardwareEnabled: false
      images:
        arm: "edgeworx/healthcare-heart-rate:arm-v1"
        x86: "edgeworx/healthcare-heart-rate:x86-v1"
      container:
        rootHostAccess: false
        ports: []
        commands:
          - '/usr/bin/contextBroker'
          - '-fg'
          - '-multiservice'
          - '-ngsiv1Autocast'
          - '-dbhost'
          - 'localhost:2017'
          - '-corsOrigin'
          - '__ALL'
      config:
          test_mode: false
          data_label: "Kilton Hopkins"
    # Simple JSON viewer for the heart rate output
    - name: heart-rate-viewer1
      agent:
        name: "neha-rpi"
      images:
        arm: "edgeworx/healthcare-heart-rate-ui:arm"
        # x86: "edgeworx/healthcare-heart-rate:x86-nano"
        x86: "edgeworx/healthcare-heart-rate-ui:x86"
      container:
        rootHostAccess: false
        ports:
          # The ui will be listening on port 80 (internal).
          - external: 5074 # You will be able to access the ui on <AGENT_IP>:5000
            internal: 80 # The ui is listening on port 80. Do not edit this.
        volumes: []
        commands:
          # This will result in the container being started as `docker run <image> <options> dbhost localhost:27017`
          - 'fg'
          - 'ngsiv1Autocast'
          - 'dbhost'
          - 'localhost:27017'
          - 'multiservice'
          - 'corsOrigin'
          - 'ALL'
        env:
          - key: "BASE_URL"
            value: "http://localhost:8080/data"
  routes:
    # Use this section to configure route between microservices
    # Use microservice name
    - name: "route"
      from: "heart-rate-monitor1"
      to: "heart-rate-viewer1"
```
Below is the `microservice.json` snippet which got stored in the agent it has cmd values in the right order as yaml.
```
...
 {
      "uuid": "DWjpB6kZjPC9XcKLTMGZTHHdVmvtnxwN",
      "imageId": "edgeworx/healthcare-heart-rate:arm-v1",
      "config": "{\"data_label\":\"Kilton Hopkins\",\"test_mode\":false}",
      "rebuild": true,
      "rootHostAccess": false,
      "logSize": 1,
      "registryId": 1,
      "portMappings": [],
      "volumeMappings": [],
      "imageSnapshot": "",
      "delete": false,
      "deleteWithCleanup": false,
      "env": [],
      "extraHosts": [],
      "cmd": [
        "/usr/bin/contextBroker",
        "-fg",
        "-multiservice",
        "-ngsiv1Autocast",
        "-dbhost",
        "localhost:2017",
        "-corsOrigin",
        "__ALL"
      ],
      "routes": [
        "PzcHcx7t3LDrZPGyjwvPC69J8fbNVNpQ"
      ],
      "isConsumer": false
    },
    {
      "uuid": "PzcHcx7t3LDrZPGyjwvPC69J8fbNVNpQ",
      "imageId": "edgeworx/healthcare-heart-rate-ui:arm",
      "config": "{}",
      "rebuild": true,
      "rootHostAccess": false,
      "logSize": 1,
      "registryId": 1,
      "portMappings": [
        {
          "portInternal": 80,
          "portExternal": 5074
        }
      ],
      "volumeMappings": [],
      "imageSnapshot": "",
      "delete": false,
      "deleteWithCleanup": false,
      "env": [
        {
          "key": "BASE_URL",
          "value": "http://localhost:8080/data"
        }
      ],
      "extraHosts": [],
      "cmd": [
        "fg",
        "ngsiv1Autocast",
        "dbhost",
        "localhost:27017",
        "multiservice",
        "corsOrigin",
        "ALL"
      ],
      "routes": [],
      "isConsumer": true
    }
...
```

So would really appreciate if you could provide us info to reproduce the issue in agent.

Thanks.

**Comment by franckOL** [comment]
Hello @NehaNaithani, 
On my side, also you have to notice that deployment done with ECN viewer

```ini
Agent: 2.0.3
Controller: v2.1.0-dev
ECN Viewer v1.0.8
iofogctl: 2.0.3 not used for deployment
```
Application template used:
```yaml

---
apiVersion: iofog.org/v2
kind: ApplicationTemplate
metadata:
  name: fiware-orion
spec:
  name: fiware-orion
  description: "◼ Main fiware-orion cloud"
  variables:
    - key: orion-deploy-id
      description: "hardware resource identifier to deploy services to"
    - key: orion-port-external
      description: "Orion IP external port"
      defaultValue: 1026
    - key: mongo-port-external
      description: "Mongo IP external port"
      defaultValue: 27017
  application: # Typical Application kind spec
    routes: []
    # List of microservices composing the application
    microservices:
      - name: mongo
        agent:
          name: "{{ orion-deploy-id }}"
          config: {}
        images:
          x86: mongo:3.6
          registry: remote
        config: {}
        container:
          volumes: []
          ports:
            - internal: 27017
              external: "{{ mongo-port-external }}"
          env: []
      - name: orion
        agent:
          name: "{{ orion-deploy-id }}"
          config: {}
        images:
          x86: fiware/orion
          registry: remote
        config: {}
        container:
          rootHostAccess: true
          volumes: []
          ports:
            - internal: 1026
              external: "{{ orion-port-external }}"
          env: []
          commands:
            - '/usr/bin/contextBroker'
            - '-fg'
            - '-multiservice'
            - '-ngsiv1Autocast'
            - '-dbhost'
            - 'localhost:{{ mongo-port-external }}'
            - '-corsOrigin'
            - '__ALL'
```
Appliction template used:
```yaml

---
apiVersion: iofog.org/v2
kind: Application
metadata:
  name: orionapp
spec:
  template:
    name: fiware-orion
    variables:
      - key: orion-deploy-id
        value: "agent-building01manager"
```

and the `microservice.json` on the agent **Pb on command order**:
```yaml
    {
      "uuid": "mnkGmy9gZg6L7gfMDL8ZLzCfRtWXBQdd",
      "imageId": "fiware/orion",
      "config": "{}",
      "rebuild": true,
      "rootHostAccess": true,
      "logSize": 50,
      "registryId": 1,
      "portMappings": [
        {
          "portInternal": 1026,
          "portExternal": 1026
        }
      ],
      "volumeMappings": [],
      "imageSnapshot": "",
      "delete": false,
      "deleteWithCleanup": false,
      "env": [],
      "extraHosts": [],
      "cmd": [
        "-corsOrigin",
        "-dbhost",
        "-fg",
        "-multiservice",
        "-ngsiv1Autocast",
        "/usr/bin/contextBroker",
        "__ALL",
        "localhost:2017"
      ],
      "routes": [],
      "isConsumer": false
    }
```

And if we look controller side, command order OK
```bash
iofogctl describe microservice orion-orionapp
```
```yaml
apiVersion: iofog.org/v2
kind: Microservice
metadata:
  name: orion-orionapp
  namespace: devmeylan
spec:
  uuid: mnkGmy9gZg6L7gfMDL8ZLzCfRtWXBQdd
  name: orion-orionapp
  agent:
    name: agent-building01manager
    config: {}
  images:
    catalogId: 0
    x86: fiware/orion
    arm: ""
    registry: remote
  container:
    commands:
    - /usr/bin/contextBroker
    - -fg
    - -multiservice
    - -ngsiv1Autocast
    - -dbhost
    - localhost:2017
    - -corsOrigin
    - __ALL
    volumes: []
    env: []
    extraHosts: []
    ports:
    - internal: 1026
      external: 1026
    rootHostAccess: true
  config: {}
  application: orionapp
```
